# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5IzO7SI7jYeDFtNpsYHCW12bdMhV5Zn
"""

import streamlit as st
import os
import qrcode
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import pagesizes
from openpyxl import Workbook, load_workbook

# ==============================
# CONFIGURACIÓN PÁGINA
# ==============================

st.set_page_config(page_title="Sistema de Evaluación", layout="centered")

st.title("📘 Sistema de Evaluación de Talleres")

# ==============================
# RÚBRICAS
# ==============================

rubricas = {
    "Organización y Presentación (20%)": {
        "peso": 20,
        "comentarios": {
            5: "Trabajo completamente ordenado, limpio y fácil de seguir. Los ejercicios están bien identificados.",
            4: "Buen orden general, con pequeños detalles de presentación.",
            3: "Presenta cierto desorden o falta de claridad en algunas partes.",
            2: "Desorganizado y difícil de seguir.",
            1: "Muy desordenado, ilegible o incompleto."
        }
    },
    "Desarrollo y Procedimiento (30%)": {
        "peso": 30,
        "comentarios": {
            5: "Muestra todos los pasos correctamente y de forma clara.",
            4: "Presenta la mayoría de los pasos con pequeños errores u omisiones.",
            3: "Faltan varios pasos importantes o hay poca explicación.",
            2: "Procedimiento incompleto o con errores graves.",
            1: "No muestra procedimiento o es totalmente incorrecto."
        }
    },
    "Exactitud de Resultados (30%)": {
        "peso": 30,
        "comentarios": {
            5: "Todos los resultados son correctos.",
            4: "Uno o dos errores menores de cálculo.",
            3: "Varios errores, pero se evidencia intento correcto.",
            2: "Muchos errores de cálculo o concepto.",
            1: "Resultados mayormente incorrectos o no responde."
        }
    },
    "Comprensión del Tema (20%)": {
        "peso": 20,
        "comentarios": {
            5: "Demuestra dominio claro de los conceptos.",
            4: "Buena comprensión general con pequeñas confusiones.",
            3: "Comprensión básica, con errores conceptuales leves.",
            2: "Dificultad notable para aplicar los conceptos.",
            1: "No demuestra comprensión del tema."
        }
    }
}

niveles = {
    5: "Excelente",
    4: "Bueno",
    3: "Aceptable",
    2: "Insuficiente",
    1: "Deficiente"
}

# ==============================
# FORMULARIO
# ==============================

asignatura = st.text_input("Asignatura")
trabajo = st.text_input("Trabajo / Taller")

cantidad = st.number_input("Número de estudiantes", min_value=1, max_value=10, value=1)

estudiantes = []
for i in range(cantidad):
    nombre = st.text_input(f"Estudiante {i+1}")
    if nombre:
        estudiantes.append(nombre)

st.subheader("Rúbricas")

valores = {}

for rubrica in rubricas:
    valores[rubrica] = st.selectbox(
        rubrica,
        options=[5,4,3,2,1],
        format_func=lambda x: f"{x} - {niveles[x]}"
    )

# ==============================
# BOTÓN GENERAR
# ==============================

if st.button("Generar Evaluación"):

    if not asignatura or not trabajo or not estudiantes:
        st.error("Debe completar todos los campos.")
    else:

        fecha_actual = datetime.now().strftime("%d/%m/%Y")

        suma = 0
        estilos = getSampleStyleSheet()
        normal = estilos["Normal"]

        filename = f"Evaluacion_{trabajo.replace(' ','_')}.pdf"
        doc = SimpleDocTemplate(filename, pagesize=pagesizes.letter)
        elements = []

        elements.append(Paragraph("<b>Evaluación de Taller</b>", estilos['Title']))
        elements.append(Spacer(1,12))
        elements.append(Paragraph(f"<b>Asignatura:</b> {asignatura}", normal))
        elements.append(Paragraph(f"<b>Trabajo:</b> {trabajo}", normal))
        elements.append(Paragraph(f"<b>Fecha:</b> {fecha_actual}", normal))
        elements.append(Spacer(1,12))

        elements.append(Paragraph("<b>Estudiantes:</b>", normal))
        for est in estudiantes:
            elements.append(Paragraph(f"- {est}", normal))

        elements.append(Spacer(1,12))

        for rubrica, info in rubricas.items():
            peso = info["peso"]
            valor = valores[rubrica]
            descripcion = niveles[valor]
            comentario = info["comentarios"][valor]

            ponderado = (valor / 5) * peso
            suma += ponderado

            elements.append(Paragraph(f"<b>{rubrica}</b>", normal))
            elements.append(Paragraph(f"Nivel: {valor} - {descripcion}", normal))
            elements.append(Paragraph(f"Comentario: {comentario}", normal))
            elements.append(Spacer(1,12))

        nota_final = round((suma / 100) * 5, 2)

        elements.append(Paragraph(f"<b>Nota Final:</b> {nota_final}", estilos["Heading2"]))

        doc.build(elements)

        # QR
        texto_qr = f"Asignatura: {asignatura}\nTrabajo: {trabajo}\nFecha: {fecha_actual}\nNota Final: {nota_final}"
        qr = qrcode.make(texto_qr)
        qr_file = "QR_Evaluacion.png"
        qr.save(qr_file)

        # Historial
        if not os.path.exists("historial.xlsx"):
            wb = Workbook()
            ws = wb.active
            ws.append(["Fecha", "Estudiantes", "Asignatura", "Trabajo", "Nota"])
            wb.save("historial.xlsx")

        wb = load_workbook("historial.xlsx")
        ws = wb.active
        ws.append([
            fecha_actual,
            ", ".join(estudiantes),
            asignatura,
            trabajo,
            nota_final
        ])
        wb.save("historial.xlsx")

        st.success(f"Evaluación generada correctamente. Nota Final: {nota_final}")

        with open(filename, "rb") as f:
            st.download_button("Descargar PDF", f, file_name=filename)

        with open(qr_file, "rb") as f:
            st.download_button("Descargar QR", f, file_name=qr_file)

        with open("historial.xlsx", "rb") as f:
            st.download_button("Descargar Historial Excel", f, file_name="historial.xlsx")

# ==============================
# BOTÓN BORRAR HISTORIAL
# ==============================

st.markdown("---")
st.subheader("Administración")

if os.path.exists("historial.xlsx"):
    if st.button("🗑️ Borrar historial completo"):
        os.remove("historial.xlsx")
        st.success("Historial eliminado correctamente.")
        st.rerun()
